### PR TITLE
Mesh update patch

### PR DESCRIPTION
**Pull request by mrquincle**
Fixes cmake build issues with external git repositories. See latest commit message for details: [f92ecdaf9ca29a046408e801ed8c092f003ea18b](https://github.com/crownstone/bluenet/commit/f92ecdaf9ca29a046408e801ed8c092f003ea18b)

### CODE REVIEW

**Comment by vliedel** [comment]
So while successfully building from master branch, when i switched to this branch and compiled as i normally do:
```
cmake .. -DBOARD_TARGET=pca593 -DDOWNLOAD_JLINK=OFF -DDOWNLOAD_NRFUTIL=OFF -DDOWNLOAD_NRFJPROG=OFF -DCONFIG_DIR=config -DCMAKE_BUILD_TYPE=Debug -DFACTORY_IMAGE=
make -j8
```

I get this output:
```
-- No download option which requires python is enabled
-- Assumed to be installed for normal development: git, wget, make
-- Assumed to be installed for tools around development: python
-- Assumed to be installed to generate releases: pass, srec_cat
-- The CPU on which CMake is running, arch=x86_64
-- Source dir /home/vliedel/dev/bluenet-workspace-cmake/bluenet
-- Build dir /home/vliedel/dev/bluenet-workspace-cmake/bluenet/build
-- Installation dir with binaries /home/vliedel/dev/bluenet-workspace-cmake/bluenet/bin
-- Search for CMake modules in /home/vliedel/dev/bluenet-workspace-cmake/bluenet/source/conf/cmake/modules/
-- Cannot find configuration file: /home/vliedel/dev/bluenet-workspace-cmake/bluenet/config/pca593/CMakeBuild.overwrite.config
-- Compiler version to use: 8-2019-q3-update
-- Board target: pca593
-- Nordic hardware development board: PCA10040
-- Use git tag 15.3.0 of repos https://github.com/crownstone/nRF5_SDK
-- Will use git tag 3.2.0 of repos https://github.com/crownstone/nRF5-SDK-for-Mesh
-- Configure nordic_sdk_15.3.0 target
-- Configure nordic_mesh_sdk_3.2.0 target
-- Configure tools target
-- The option AUTO_UPDATE_TOOLS is set to OFF.
-- This means no download/update of binary logging, nrfutil, etc. on `make bluenet`.
-- Download/update can still be done manually (if they are configured).
-- For example, when configured with -DDOWNLOAD_NRFUTIL=ON, call `make tools` subsequently.
-- Configure write_softdevice target
-- Configure write_mbr_param_address target
-- Configure read_softdevice_version target
-- Configure erase target
-- Configure reset target
-- Configure pca593 target
-- Configure debug_application target
-- Configure write_board_version target
-- Configure write_application target
-- Configure write_bootloader target
-- Configure create_git_release target
-- Configure create_git_release_bootloader target
-- Configuring done
-- Generating done
-- Build files have been written to: /home/vliedel/dev/bluenet-workspace-cmake/bluenet/build
Scanning dependencies of target nordic_sdk_15.3.0
Scanning dependencies of target nordic_mesh_sdk_3.2.0
[  8%] Run make depend in target directory
[  8%] Install supporting tools
[ 28%] Built target gcc_arm_none_eabi
make[3]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
[ 31%] Creating directories for 'nordic_sdk_15.3.0'
[ 34%] Creating directories for 'nordic_mesh_sdk_3.2.0'
-- Install supporting tools
[ 34%] Built target tools
-- Bluetooth name BART
-- PATH is set to: :/home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/gcc_arm_none_eabi/bin
-- C Compiler: /home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/gcc_arm_none_eabi/bin/arm-none-eabi-gcc
-- C++ Compiler: /home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/gcc_arm_none_eabi/bin/arm-none-eabi-g++
-- Search for FindX files in ;/home/vliedel/dev/bluenet-workspace-cmake/bluenet/source/conf;/home/vliedel/dev/bluenet-workspace-cmake/bluenet/source/conf/cmake;/home/vliedel/dev/bluenet-workspace-cmake/bluenet/source/conf/cmake/modules;/home/vliedel/dev/bluenet-workspace-cmake/bluenet/source/conf/cmake
-- crownstone.defs.cmake: Build type: "Debug"
-- Crownstone serial enabled
-- Apply PAN 74 workaround
-- Note! Interprocedural optimization not enabled (might just be because cmake does not know if the compiler supports it)
-- Pay attention, this is a debug build (change with -DCMAKE_BUILD_TYPE=Release or RelWithDebInfo
-- CXX flags: -std=c++17 -fno-exceptions -fdelete-dead-exceptions -fno-unwind-tables -fno-non-call-exceptions -mthumb -ffunction-sections -fdata-sections -Wall -Werror -fdiagnostics-color=always -fno-strict-aliasing -fno-builtin -fshort-enums -Wno-error=format -Wno-error=unused-function -Os -fomit-frame-pointer -mcpu=cortex-m4 -mfloat-abi=hard -mfpu=fpv4-sp-d16
-- C flags:  -mthumb -ffunction-sections -fdata-sections -Wall -Werror -fdiagnostics-color=always -fno-strict-aliasing -fno-builtin -fshort-enums -Wno-error=format -Wno-error=unused-function -Os -fomit-frame-pointer -mcpu=cortex-m4 -mfloat-abi=hard -mfpu=fpv4-sp-d16
-- Search for FindX files in ;/home/vliedel/dev/bluenet-workspace-cmake/bluenet/source/conf;/home/vliedel/dev/bluenet-workspace-cmake/bluenet/source/conf/cmake;/home/vliedel/dev/bluenet-workspace-cmake/bluenet/source/conf/cmake/modules;/home/vliedel/dev/bluenet-workspace-cmake/bluenet/source/conf/cmake;;/home/vliedel/dev/bluenet-workspace-cmake/bluenet/source/conf/cmake/modules;/home/vliedel/dev/bluenet-workspace-cmake/bluenet/source/conf/cmake/modules/third
-- Git branch refs/heads/mesh-update-patch at hash f92ecdaf9ca29a046408e801ed8c092f003ea18b
-- Hardware board: PCA10040
-- Set verbosity to level: 4
-- Compiler: /home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/gcc_arm_none_eabi/bin/arm-none-eabi-gcc
-- Do not set application start address
-- NRF5_DIR: /home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/nrf5_sdk/15.3.0
-- Use directory /home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/mesh_sdk/3.2.0 for the mesh
-- SERIAL from NORDIC disabled
-- Module for twi disabled
-- Module for gpio tasks and events disabled
[ 37%] Performing download step (git clone) for 'nordic_sdk_15.3.0'
-- Bootloader version: 2.1.0
-- Descend into bootloader directory and compile if needed
-- bootloader: Search for FindX files in /home/vliedel/dev/bluenet-workspace-cmake/bluenet/source/conf;/home/vliedel/dev/bluenet-workspace-cmake/bluenet/source/conf/cmake;/home/vliedel/dev/bluenet-workspace-cmake/bluenet/source/conf/cmake/modules;/home/vliedel/dev/bluenet-workspace-cmake/bluenet/source/conf/cmake;/home/vliedel/dev/bluenet-workspace-cmake/bluenet/source/conf/cmake/modules;/home/vliedel/dev/bluenet-workspace-cmake/bluenet/source/conf/cmake/modules/third;/home/vliedel/dev/bluenet-workspace-cmake/bluenet/source/conf/cmake/modules
-- bootloader: Set verbosity to level: 4
-- bootloader: Compiler: /home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/gcc_arm_none_eabi/bin/arm-none-eabi-gcc
[ 40%] Performing download step (git clone) for 'nordic_mesh_sdk_3.2.0'
-- bootloader: nrf log: 0
-- bootloader: SERIAL log disabled
-- Set bootloader build type: 1
-- Bootloader version: 2
-- bootloader: Configure nrf_symbols.ld file
-- bootloader: Configure cs_BootloaderConfig.cpp file
-- bootloader: Configure cs_config.h file
-- bootloader: Bootloader parameters: 0x00076000, 0x8000
-- Remove sections .uicr_bootloader_start_address and .uicr_mbr_params_page (or objcopy will generate huge files)
-- bootloader: Target pca593
-- Configure cs_Git.cpp file
-- Configure cs_AutoConfig.cpp file
-- Configure cs_StaticConfig.h file
-- Configure cs_config.h file
-- Configure nrf_symbols.ld file
-- Application start address: 0x00026000
-- Application length: 0x50000
-- RAM base: 0x20002A00
-- RAM amount: 0xD600
-- RAM for IPC: 0x100
-- Include path: include/third/nrf
-- Include path: include/third/nrf/sdk15.3.0
-- Persistent flags disabled: 
-- Get version for hardware "PCA10040"
-- Search for board name PCA10040 in header file
-- Found PCA10040 (it has indeed version 41)
-- Got 41
-- Hexadecimal 0x00000029
-- Already released... No create_release_in_repository target available
-- Already released... No create_bootloader_release_in_repository target available
-- Write variables to /home/vliedel/dev/bluenet-workspace-cmake/bluenet/build/pca593/list_variables.txt
-- Configuring done
CMake Error at CMakeLists.txt:509 (add_executable):
  Cannot find source file:

    /home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/mesh_sdk/3.2.0/mesh/core/src/nrf_mesh_utils.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx


CMake Error: CMake can not determine linker language for target: crownstone
CMake Error: Cannot determine link language for target "crownstone".
Cloning into '3.2.0'...
-- Generating done
-- Build files have been written to: /home/vliedel/dev/bluenet-workspace-cmake/bluenet/build/pca593
Makefile:156: recipe for target 'depend' failed
make[3]: *** [depend] Error 1
-- First install
[ 40%] Built target target_depend
Cloning into '15.3.0'...
HEAD is now at ce27872 Patch alignment issue: taking address of packed member
[ 45%] Performing patch step for 'nordic_mesh_sdk_3.2.0'
[ 45%] Performing update step for 'nordic_mesh_sdk_3.2.0'
Skipping patch step.
HEAD is up to date.
[ 48%] Performing configure step for 'nordic_mesh_sdk_3.2.0'
Skipping configure step.
[ 51%] Performing build step for 'nordic_mesh_sdk_3.2.0'
Skipping build step.
[ 54%] Performing install step for 'nordic_mesh_sdk_3.2.0'
Skipping install step.
[ 57%] Completed 'nordic_mesh_sdk_3.2.0'
[ 57%] Built target nordic_mesh_sdk_3.2.0
Checking out files: 100% (11822/11822), done.
HEAD is now at f47f020c Crownstone patches
[ 62%] No patch step for 'nordic_sdk_15.3.0'
[ 62%] Performing update step for 'nordic_sdk_15.3.0'
HEAD is up to date.
[ 65%] Performing configure step for 'nordic_sdk_15.3.0'
Skipping configure step.
[ 68%] Performing build step for 'nordic_sdk_15.3.0'
Skipping build step.
[ 71%] Performing install step for 'nordic_sdk_15.3.0'
Skipping install step.
[ 74%] Completed 'nordic_sdk_15.3.0'
[ 74%] Built target nordic_sdk_15.3.0
[ 77%] Build micro-eec
micro-ecc not found! Let's pull it from HEAD.
Cloning into 'micro-ecc'...
remote: Enumerating objects: 1143, done.
remote: Counting objects: 100% (48/48), done.
remote: Compressing objects: 100% (37/37), done.
remote: Total 1143 (delta 21), reused 28 (delta 9), pack-reused 1095
Receiving objects: 100% (1143/1143), 687.07 KiB | 9.41 MiB/s, done.
Resolving deltas: 100% (664/664), done.
make[3]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
Compiling file: uECC.c
Creating library: ../../nrf51_armgcc/armgcc/micro_ecc_lib_nrf51.a
/home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/gcc_arm_none_eabi/bin/arm-none-eabi-ar: creating ../../nrf51_armgcc/armgcc/micro_ecc_lib_nrf51.a
Done
make[3]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
Compiling file: uECC.c
Creating library: ../../nrf51_iar/armgcc/micro_ecc_lib_nrf51.a
/home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/gcc_arm_none_eabi/bin/arm-none-eabi-ar: creating ../../nrf51_iar/armgcc/micro_ecc_lib_nrf51.a
Done
make[3]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
Compiling file: uECC.c
Creating library: ../../nrf51_keil/armgcc/micro_ecc_lib_nrf51.lib
/home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/gcc_arm_none_eabi/bin/arm-none-eabi-ar: creating ../../nrf51_keil/armgcc/micro_ecc_lib_nrf51.lib
Done
make[3]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
Compiling file: uECC.c
Creating library: ../../nrf52hf_armgcc/armgcc/micro_ecc_lib_nrf52.a
/home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/gcc_arm_none_eabi/bin/arm-none-eabi-ar: creating ../../nrf52hf_armgcc/armgcc/micro_ecc_lib_nrf52.a
Done
make[3]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
Compiling file: uECC.c
Creating library: ../../nrf52hf_iar/armgcc/micro_ecc_lib_nrf52.a
/home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/gcc_arm_none_eabi/bin/arm-none-eabi-ar: creating ../../nrf52hf_iar/armgcc/micro_ecc_lib_nrf52.a
Done
make[3]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
Compiling file: uECC.c
Creating library: ../../nrf52hf_keil/armgcc/micro_ecc_lib_nrf52.lib
/home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/gcc_arm_none_eabi/bin/arm-none-eabi-ar: creating ../../nrf52hf_keil/armgcc/micro_ecc_lib_nrf52.lib
Done
make[3]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
Compiling file: uECC.c
Creating library: ../../nrf52nf_armgcc/armgcc/micro_ecc_lib_nrf52.a
/home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/gcc_arm_none_eabi/bin/arm-none-eabi-ar: creating ../../nrf52nf_armgcc/armgcc/micro_ecc_lib_nrf52.a
Done
make[3]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
Compiling file: uECC.c
Creating library: ../../nrf52nf_iar/armgcc/micro_ecc_lib_nrf52.a
/home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/gcc_arm_none_eabi/bin/arm-none-eabi-ar: creating ../../nrf52nf_iar/armgcc/micro_ecc_lib_nrf52.a
Done
make[3]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
Compiling file: uECC.c
Creating library: ../../nrf52nf_keil/armgcc/micro_ecc_lib_nrf52.lib
/home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/gcc_arm_none_eabi/bin/arm-none-eabi-ar: creating ../../nrf52nf_keil/armgcc/micro_ecc_lib_nrf52.lib
Done
[ 77%] Built target micro_eec
[ 80%] Performing build step for 'bluenet'
Scanning dependencies of target crownstone
make[5]: *** No rule to make target 'CMakeFiles/crownstone.dir/build'.  Stop.
CMakeFiles/Makefile2:611: recipe for target 'CMakeFiles/crownstone.dir/all' failed
make[4]: *** [CMakeFiles/crownstone.dir/all] Error 2
make[4]: *** Waiting for unfinished jobs....
Scanning dependencies of target bootloader
[  1%] Building C object bootloader/CMakeFiles/bootloader.dir/dfu_public_key.c.o
[  3%] Building C object bootloader/CMakeFiles/bootloader.dir/__/shared/ipc/cs_IpcRamData.c.o
[  4%] Building C object bootloader/CMakeFiles/bootloader.dir/home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/nrf5_sdk/15.3.0/modules/nrfx/mdk/gcc_startup_nrf52.S.o
[  6%] Building C object bootloader/CMakeFiles/bootloader.dir/main.c.o
[  7%] Building C object bootloader/CMakeFiles/bootloader.dir/__/src/cfg/cs_Boards.c.o
[  9%] Building C object bootloader/CMakeFiles/bootloader.dir/dev_info_service.c.o
[  9%] Building C object bootloader/CMakeFiles/bootloader.dir/home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/nrf5_sdk/15.3.0/modules/nrfx/mdk/system_nrf52.c.o
[ 11%] Building C object bootloader/CMakeFiles/bootloader.dir/home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/nrf5_sdk/15.3.0/components/ble/ble_services/ble_dis/ble_dis.c.o
[ 12%] Building C object bootloader/CMakeFiles/bootloader.dir/home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/nrf5_sdk/15.3.0/components/libraries/util/app_error_weak.c.o
[ 14%] Building C object bootloader/CMakeFiles/bootloader.dir/home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/nrf5_sdk/15.3.0/components/libraries/scheduler/app_scheduler.c.o
[ 15%] Building C object bootloader/CMakeFiles/bootloader.dir/home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/nrf5_sdk/15.3.0/components/libraries/util/app_util_platform.c.o
[ 17%] Building C object bootloader/CMakeFiles/bootloader.dir/home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/nrf5_sdk/15.3.0/components/libraries/crc32/crc32.c.o
[ 19%] Building C object bootloader/CMakeFiles/bootloader.dir/home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/nrf5_sdk/15.3.0/components/libraries/mem_manager/mem_manager.c.o
[ 20%] Building C object bootloader/CMakeFiles/bootloader.dir/home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/nrf5_sdk/15.3.0/components/libraries/util/nrf_assert.c.o
[ 22%] Building C object bootloader/CMakeFiles/bootloader.dir/home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/nrf5_sdk/15.3.0/components/libraries/atomic_fifo/nrf_atfifo.c.o
[ 22%] Building C object bootloader/CMakeFiles/bootloader.dir/home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/nrf5_sdk/15.3.0/components/libraries/atomic/nrf_atomic.c.o
[ 23%] Building C object bootloader/CMakeFiles/bootloader.dir/home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/nrf5_sdk/15.3.0/components/libraries/balloc/nrf_balloc.c.o
[ 25%] Building C object bootloader/CMakeFiles/bootloader.dir/home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/nrf5_sdk/15.3.0/components/libraries/fstorage/nrf_fstorage.c.o
[ 26%] Building C object bootloader/CMakeFiles/bootloader.dir/home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/nrf5_sdk/15.3.0/components/libraries/fstorage/nrf_fstorage_nvmc.c.o
[ 28%] Building C object bootloader/CMakeFiles/bootloader.dir/home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/nrf5_sdk/15.3.0/components/libraries/fstorage/nrf_fstorage_sd.c.o
[ 30%] Building C object bootloader/CMakeFiles/bootloader.dir/home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/nrf5_sdk/15.3.0/components/libraries/queue/nrf_queue.c.o
[ 31%] Building C object bootloader/CMakeFiles/bootloader.dir/home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/nrf5_sdk/15.3.0/components/libraries/experimental_section_vars/nrf_section_iter.c.o
[ 33%] Building C object bootloader/CMakeFiles/bootloader.dir/home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/nrf5_sdk/15.3.0/components/libraries/strerror/nrf_strerror.c.o
[ 34%] Building C object bootloader/CMakeFiles/bootloader.dir/home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/nrf5_sdk/15.3.0/components/libraries/sha256/sha256.c.o
[ 34%] Building C object bootloader/CMakeFiles/bootloader.dir/home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/nrf5_sdk/15.3.0/components/libraries/crypto/backend/micro_ecc/micro_ecc_backend_ecc.c.o
[ 36%] Building C object bootloader/CMakeFiles/bootloader.dir/home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/nrf5_sdk/15.3.0/components/libraries/crypto/backend/micro_ecc/micro_ecc_backend_ecdh.c.o
[ 38%] Building C object bootloader/CMakeFiles/bootloader.dir/home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/nrf5_sdk/15.3.0/components/libraries/crypto/backend/micro_ecc/micro_ecc_backend_ecdsa.c.o
[ 39%] Building C object bootloader/CMakeFiles/bootloader.dir/home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/nrf5_sdk/15.3.0/modules/nrfx/hal/nrf_nvmc.c.o
[ 41%] Building C object bootloader/CMakeFiles/bootloader.dir/home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/nrf5_sdk/15.3.0/components/libraries/crypto/nrf_crypto_ecc.c.o
[ 42%] Building C object bootloader/CMakeFiles/bootloader.dir/home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/nrf5_sdk/15.3.0/components/libraries/crypto/nrf_crypto_ecdsa.c.o
[ 44%] Building C object bootloader/CMakeFiles/bootloader.dir/home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/nrf5_sdk/15.3.0/components/libraries/crypto/nrf_crypto_hash.c.o
[ 46%] Building C object bootloader/CMakeFiles/bootloader.dir/home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/nrf5_sdk/15.3.0/components/libraries/crypto/nrf_crypto_init.c.o
[ 46%] Building C object bootloader/CMakeFiles/bootloader.dir/home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/nrf5_sdk/15.3.0/components/libraries/crypto/nrf_crypto_shared.c.o
[ 47%] Building C object bootloader/CMakeFiles/bootloader.dir/home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/nrf5_sdk/15.3.0/components/ble/common/ble_srv_common.c.o
[ 49%] Building C object bootloader/CMakeFiles/bootloader.dir/nrf_bootloader.c.o
[ 50%] Building C object bootloader/CMakeFiles/bootloader.dir/home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/nrf5_sdk/15.3.0/components/libraries/bootloader/nrf_bootloader_app_start.c.o
[ 52%] Building C object bootloader/CMakeFiles/bootloader.dir/home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/nrf5_sdk/15.3.0/components/libraries/bootloader/nrf_bootloader_app_start_final.c.o
[ 53%] Building C object bootloader/CMakeFiles/bootloader.dir/home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/nrf5_sdk/15.3.0/components/libraries/bootloader/nrf_bootloader_dfu_timers.c.o
[ 55%] Building C object bootloader/CMakeFiles/bootloader.dir/home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/nrf5_sdk/15.3.0/components/libraries/bootloader/nrf_bootloader_fw_activation.c.o
[ 57%] Building C object bootloader/CMakeFiles/bootloader.dir/home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/nrf5_sdk/15.3.0/components/libraries/bootloader/nrf_bootloader_info.c.o
[ 58%] Building C object bootloader/CMakeFiles/bootloader.dir/home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/nrf5_sdk/15.3.0/components/libraries/bootloader/nrf_bootloader_wdt.c.o
[ 58%] Building C object bootloader/CMakeFiles/bootloader.dir/home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/nrf5_sdk/15.3.0/external/nano-pb/pb_common.c.o
[ 60%] Building C object bootloader/CMakeFiles/bootloader.dir/home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/nrf5_sdk/15.3.0/external/nano-pb/pb_decode.c.o
[ 61%] Building C object bootloader/CMakeFiles/bootloader.dir/home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/nrf5_sdk/15.3.0/components/libraries/crypto/backend/nrf_sw/nrf_sw_backend_hash.c.o
[ 63%] Building C object bootloader/CMakeFiles/bootloader.dir/home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/nrf5_sdk/15.3.0/components/libraries/bootloader/dfu/dfu-cc.pb.c.o
[ 65%] Building C object bootloader/CMakeFiles/bootloader.dir/home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/nrf5_sdk/15.3.0/components/libraries/bootloader/dfu/nrf_dfu.c.o
[ 66%] Building C object bootloader/CMakeFiles/bootloader.dir/nrf_dfu_ble.c.o
[ 68%] Building C object bootloader/CMakeFiles/bootloader.dir/home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/nrf5_sdk/15.3.0/components/libraries/bootloader/dfu/nrf_dfu_flash.c.o
[ 69%] Building C object bootloader/CMakeFiles/bootloader.dir/home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/nrf5_sdk/15.3.0/components/libraries/bootloader/dfu/nrf_dfu_handling_error.c.o
[ 71%] Building C object bootloader/CMakeFiles/bootloader.dir/home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/nrf5_sdk/15.3.0/components/libraries/bootloader/dfu/nrf_dfu_mbr.c.o
[ 71%] Building C object bootloader/CMakeFiles/bootloader.dir/home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/nrf5_sdk/15.3.0/components/libraries/bootloader/dfu/nrf_dfu_req_handler.c.o
[ 73%] Building C object bootloader/CMakeFiles/bootloader.dir/home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/nrf5_sdk/15.3.0/components/libraries/bootloader/dfu/nrf_dfu_settings.c.o
[ 74%] Building C object bootloader/CMakeFiles/bootloader.dir/home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/nrf5_sdk/15.3.0/components/libraries/bootloader/dfu/nrf_dfu_settings_svci.c.o
[ 76%] Building C object bootloader/CMakeFiles/bootloader.dir/home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/nrf5_sdk/15.3.0/components/libraries/bootloader/dfu/nrf_dfu_transport.c.o
[ 77%] Building C object bootloader/CMakeFiles/bootloader.dir/home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/nrf5_sdk/15.3.0/components/libraries/bootloader/dfu/nrf_dfu_utils.c.o
[ 79%] Building C object bootloader/CMakeFiles/bootloader.dir/home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/nrf5_sdk/15.3.0/components/libraries/bootloader/dfu/nrf_dfu_validation.c.o
[ 80%] Building C object bootloader/CMakeFiles/bootloader.dir/home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/nrf5_sdk/15.3.0/components/libraries/bootloader/dfu/nrf_dfu_ver_validation.c.o
[ 80%] Building C object bootloader/CMakeFiles/bootloader.dir/home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/nrf5_sdk/15.3.0/components/libraries/svc/nrf_svc_handler.c.o
[ 82%] Building C object bootloader/CMakeFiles/bootloader.dir/home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/nrf5_sdk/15.3.0/components/libraries/bootloader/dfu/nrf_dfu_svci_handler.c.o
[ 84%] Building C object bootloader/CMakeFiles/bootloader.dir/home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/nrf5_sdk/15.3.0/components/softdevice/common/nrf_sdh.c.o
[ 85%] Building C object bootloader/CMakeFiles/bootloader.dir/home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/nrf5_sdk/15.3.0/components/softdevice/common/nrf_sdh_ble.c.o
[ 87%] Building C object bootloader/CMakeFiles/bootloader.dir/home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/nrf5_sdk/15.3.0/components/softdevice/common/nrf_sdh_soc.c.o
[ 88%] Building C object bootloader/CMakeFiles/bootloader.dir/home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/nrf5_sdk/15.3.0/components/libraries/crypto/backend/oberon/oberon_backend_chacha_poly_aead.c.o
[ 90%] Building C object bootloader/CMakeFiles/bootloader.dir/home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/nrf5_sdk/15.3.0/components/libraries/crypto/backend/oberon/oberon_backend_ecc.c.o
[ 92%] Building C object bootloader/CMakeFiles/bootloader.dir/home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/nrf5_sdk/15.3.0/components/libraries/crypto/backend/oberon/oberon_backend_ecdh.c.o
[ 93%] Building C object bootloader/CMakeFiles/bootloader.dir/home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/nrf5_sdk/15.3.0/components/libraries/crypto/backend/oberon/oberon_backend_ecdsa.c.o
[ 95%] Building C object bootloader/CMakeFiles/bootloader.dir/home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/nrf5_sdk/15.3.0/components/libraries/crypto/backend/oberon/oberon_backend_eddsa.c.o
[ 95%] Building C object bootloader/CMakeFiles/bootloader.dir/home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/nrf5_sdk/15.3.0/components/libraries/crypto/backend/oberon/oberon_backend_hash.c.o
[ 96%] Building C object bootloader/CMakeFiles/bootloader.dir/home/vliedel/dev/bluenet-workspace-cmake/bluenet/tools/nrf5_sdk/15.3.0/components/libraries/crypto/backend/oberon/oberon_backend_hmac.c.o
[ 98%] Building C object bootloader/CMakeFiles/bootloader.dir/cs_BootloaderConfig.c.o
[100%] Linking C executable bootloader.elf
   text	   data	    bss	    dec	    hex	filename
  29516	    184	  18080	  47780	   baa4	bootloader.elf
** Firmware size : 1666148 bytes
** bootloader: Remove UICR sections for start address and MBR parameters
[100%] Built target bootloader
Makefile:129: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/bluenet.dir/build.make:110: recipe for target 'pca593/stamp/bluenet-build' failed
make[2]: *** [pca593/stamp/bluenet-build] Error 2
CMakeFiles/Makefile2:599: recipe for target 'CMakeFiles/bluenet.dir/all' failed
make[1]: *** [CMakeFiles/bluenet.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by mrquincle** [comment]
Yes, that's exactly the problem on the `master` branch. It checks out only a shallow copy of the github repositories.

**Comment by vliedel** [comment]
Ok, so after running make clean, it worked fine :)

**Comment by mrquincle** [comment]
Ah, no, I see there's another issue here that has to do with parallel builds.

**Comment by mrquincle** [comment]
It's probably also present in master, I'll try to write another patch for it:

+ First mesh code gets downloaded.
+ Then the crownstone target is configured (CMakeLists.txt:509) on which moment files are missing.
+ Only after that the update runs for mesh.

Not only will a `make clean` "fix" this, a `make` without `-j` option would not have encountered it either. I'll take a look nevertheless.

**Pull request merged**
